language: node_js
node_js:
- '10'

deploy:
  provider: npm
  email: desk.abhimanyu@gmail.com
  api_key:
    secure: "frJquv0Iu7kCGeV7b0N/XhN5Yy3/qaFGybY/tTToNv59NioOWQEvqY5PsG2iol/HNZLHnVuwUQdB7SaiQHmjqKiilNTqbvOdd8rWnIk5MfHVbFD9kRtIo8kPRL5kBypRW6Kcf4x250cUjU3QkyvK5x+vpRSKnjqRHogWpq0gscQRZn6WGbL
RRwWExGPTDwn3N1siMb5RGSvzyY7+ZO8VuUoXYb+lyo7dazKlIUPNy9QIyi1AL9nNVxdECgnfe2zivYHI07H2NVKhDmkMtgv2qDX4FiXQy6Z1XYJkyLmHHv81tbwU6doaIOkldEUC9yvAR8gIporKQfLsOP4g+AyyhuSTQaMzJRk3C0+qJWZd1g7AKb0yk
vhaOhWaZEJCN9UaAEw0fcdB23S+JEqVUEdHCx85dnEDo6CBiKtFV3pL+IU8U1EARmvxUgw5TlVDREGXc1MsBnFsnHlagHN25NtaVcfJuTZxyhkEIuvDD2NP4pUqhfptO4Wn4uMIyf8wsmYcrU37bKqEEf65L5MUvMfRxNf5s7pldrTM/pto1ddj3uzEtw0
PgppLgM9+YJgDeevX3C+LPzEGDz2FHk1Lah/SmDoO8NbkaPOSwhVJ8hcmKcjYi20KOZJrp5ZrCiCHbER/bAJFSUJ3i4KVM0qmeZbT2gkdJP51wjiu4NyUpVh7LEg="
